name: SBroadcast
main: io.github.son588.SBroadcast.Main
version: 1.0
#Commands
commands:
   bc:
      description: Broadcast a message!
      permission: sbc.broadcast
      permission-message: You can't broadcast a message. :,( Wish ya could (In a decade)

#Permissions
permissions:
    sbc.broadcast:
        description: Allows player to use /sbc
        default: op
